version: '3.9'

services:
  database:
    image: postgres
    container_name: database_practice
    restart: always
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=marcelo
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=practice
    volumes:
      - pgdata:/data/postgres

  
  app:
    build: .
    container_name: app_practice
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database
    
volumes:
  pgdata:
    driver: local

